#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-treelayout
Version  : 1.0.3
Release  : 1
URL      : https://github.com/abego/treelayout/archive/v1.0.3.tar.gz
Source0  : https://github.com/abego/treelayout/archive/v1.0.3.tar.gz
Source1  : https://repo1.maven.org/maven2/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar
Source2  : https://repo1.maven.org/maven2/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-treelayout-data = %{version}-%{release}

%description
# abego TreeLayout
__Efficient and Customizable Tree Layout Algorithm in Java__
The TreeLayout creates tree layouts for arbitrary trees. It is not restricted to a specific output or format, but can be used for any kind of two dimensional diagram. Examples are Swing based components, SVG files, and many more. This is possible because TreeLayout separates the layout of a tree from the actual rendering.

%package data
Summary: data components for the mvn-treelayout package.
Group: Data

%description data
data components for the mvn-treelayout package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar
/usr/share/java/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.pom
